sudo: false
language: node_js
node_js:
- stable
before_install:
- npm install -g gulp
install:
- travis_retry npm install
after_success:
- gulp coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
before_deploy:
- gulp build
deploy:
  - provider: npm
    email: j.andrichak@rackspace.com
    skip_cleanup: true
    on:
      tags: true
    api_key:
      secure: M+mUJZ12L6/LotBloBL7J38mi3wFsYN7xByefE3V6ClMsNjoSJ+4nGW14aGFw4fCfESJx/n55Wub7gadt3xx7bS2Op3p8HQ3kv2eKXlR9WoljUpoqPmqxbn5KvftoiHh0+D32eZVMFN5wNoMANT1hRKcS2gY7u9KXAMXsEB0/yY=
